targets:
  $default:
    builders:
      stacked_generator|stackedRouterBuilder:
        generate_for:
          include: []
      stacked_generator|stackedLocatorBuilder:
        generate_for:
          include: []
