// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvom7smU4JLy4apVeRNrWjIgYLIfj5y0M',
    appId: '1:207833844155:web:cdf63a42b41e8eea399c9e',
    messagingSenderId: '207833844155',
    projectId: 'regardless-social-api',
    authDomain: 'regardless-social-api.firebaseapp.com',
    storageBucket: 'regardless-social-api.appspot.com',
    measurementId: 'G-431S1PQK1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8w14yzjHUN5o7P-bJ4247kSNJUD4S_Ms',
    appId: '1:207833844155:android:dfd5bb5e150c2668399c9e',
    messagingSenderId: '207833844155',
    projectId: 'regardless-social-api',
    storageBucket: 'regardless-social-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz4ZQSe-5ZmPgfCzYWUl6_urpNUh7NjA',
    appId: '1:207833844155:ios:b5343c6747e7c88c399c9e',
    messagingSenderId: '207833844155',
    projectId: 'regardless-social-api',
    storageBucket: 'regardless-social-api.appspot.com',
    androidClientId:
        '207833844155-6t60jkkldvaq79fo9ufqspht5ge2tfgo.apps.googleusercontent.com',
    iosClientId:
        '207833844155-vjp1rv2t1a0qeta6vll8mofafbd8es90.apps.googleusercontent.com',
    iosBundleId: 'com.regardlessmode.app',
  );
}
